# Generated by Django 5.0.3 on 2024-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField(default=0)),
                ('y_coord', models.FloatField(default=0)),
                ('z_coord', models.FloatField(default=0)),
            ],
        ),
    ]
